blog/urls.py
from django.urls import path
from . import views


urlpatterns=[
   path('blogs/', views.blog, name="blogs"),
   path('create-blog/',views.createBlog, name="createblog"),
   path('blog-details/<slug:slug>', views.details, name="blogdetail"),
   path('update-blog/<str:pk>/', views.updateBlog, name="updateblog"),
   path('delete-blog/<str:pk>/', views.deleteBlog, name="deleteBlog"),
]

setting/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve 

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('recipes.urls')),
    path('', include('blog.urls')),
    path('',include('main.urls')),
    path('notification/',include('notification.urls')),

    #Reset Password

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="confirm_password.html"), name="password_reset_complete")

]

handler404 = 'main.views.error_404_view'
handler500 = 'main.views.error_500'

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]


admin.site.site_header = "yemake.com"
admin.site.site_title = "YeMake"

blog/models.py
from email.policy import default
from django.db import models
from blog.helper import seo
from django.utils.crypto import get_random_string
from users.models import Profile
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from django_quill.fields import QuillField


class Category(models.Model):
    title=models.CharField(max_length=250)
    def __str__(self):
        return self.title


class Blog(models.Model):
    title=models.CharField(max_length=250)
    description=QuillField()
    image= image=models.ImageField(default='Blog/default.png', upload_to='Blog', null=True)
    isActive=models.BooleanField(default=False)
    inSlide=models.BooleanField(default=False)
    slug=models.SlugField(editable=False, verbose_name="Slug", unique=True, null=True)
    created=models.DateTimeField(auto_now_add=True, null=True)
    category= models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    owner=models.name = models.ForeignKey(Profile, related_name='blogown', on_delete=models.CASCADE, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
     related_query_name='hit_count_generic_relation')

    def save(self, *arg, **kargs):  
        if Blog.objects.filter(title=self.title):
            self.slug=seo(self.title)+get_random_string(length=4)
        else:
            self.slug = seo(self.title)
        super().save(arg,kargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering=["-created"]

recipes/models.py

from django.db import models
from recipes.helper import seo
from django.utils.crypto import get_random_string
from users.models import Profile
from embed_video.fields  import  EmbedVideoField
from django_quill.fields import QuillField
from django.utils.text import slugify



# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=250)
    image=models.ImageField(null=True,upload_to='Category')
    slug=models.SlugField(editable=False, verbose_name="Slug", null=True, unique=True)

    def __str__(self):
        return self.title

    def save(self, *arg, **kargs):
        if Category.objects.filter(title=self.title):
            self.slug=seo(self.title)+get_random_string(length=4)
        else:
            self.slug = seo(self.title)
        super().save(arg,kargs)
    
    class Meta:
        verbose_name="Kateqoriya"
        verbose_name_plural="Kateqoriyalar"


class Blog(models.Model):
    sn = 'saniyə'
    deq = 'dəqiqə'
    s = 'saat'
    g = 'gün'

    TIME_CHOICES = [
        (sn, "saniyə"),
        (deq, 'dəqiqə'),
        (s, 'saat'),
        (g, 'gün'),
       
    ]
    title = models.CharField(verbose_name="Başlıq",max_length=1500)
    description = QuillField(verbose_name="Açıqlama")
    image=models.ImageField(verbose_name="Şəkil",null=True, blank=True, default='Recipes/default.jpg', upload_to='Recipes')
    isActive=models.BooleanField(verbose_name="Aktivlik",default=False)
    category= models.ForeignKey(Category,verbose_name="Kateqoriya", on_delete=models.CASCADE)
    slug=models.SlugField(editable=False, verbose_name="Slug", null=True, unique=True)
    cook_time=models.IntegerField(verbose_name="Bişirilmə Vaxtı",null=True)
    time=models.CharField(verbose_name="Zaman Ölçüsü",max_length=10, choices=TIME_CHOICES, default=deq, null=True)
    created=models.DateTimeField("Yaradılma Vaxtı",auto_now_add=True, null=True)
    youtube_link=EmbedVideoField("Youtube Linki",null=True, blank=True)
    owner=models.ForeignKey(Profile,verbose_name="Postu Paylaşan", null=True, on_delete=models.SET_NULL)
    
    def save(self, *arg, **kargs):
        if Blog.objects.filter(title=self.title):
            slug=seo(self.title)+get_random_string(length=4)
            self.slug=slugify(slug)
        else:
            slug = seo(self.title)
            self.slug=slugify(slug)
        super().save(arg,kargs)
    
    def __str__(self):
        return self.title
    class Meta:
        ordering= ["-created"]
        verbose_name="Resept"
        verbose_name_plural="Reseptlər"


class Review(models.Model):
    owner=models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Blog ,on_delete=models.CASCADE)
    body=models.TextField(null=True,blank=False)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.body
    class Meta:
        ordering=["-created"]
        verbose_name="Şərh"
        verbose_name_plural="Şərhlər"

class Vote(models.Model):
    owner=models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        unique_together=[["owner", "recipe"]]
        verbose_name="Bəyənmə"
        verbose_name_plural="Bəyənmələr"

    def __str__(self):
        return self.recipe.title



class RecipeBook(models.Model):
    owner=models.ForeignKey(Profile,on_delete=models.CASCADE, null=True)
    recipe=models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.recipe.owner)
    class Meta:
        unique_together=[["owner", "recipe"]]
        verbose_name="Resept Dəftəri"
        verbose_name_plural="Resept Dəftəri"
    

templates/partials/__blogcard.html
{% load static %}
{% load hitcount_tags %}

<div class="post-card">
    {% if blog.isActive %}
    {% else %}
    <div class="time-cook pending">Gözləmədədir</div>
    {% endif %}
    {% if blog.owner.id == user.profile.id %}
    <div class="dots">
        <i class="fa-solid fa-ellipsis-vertical"></i>
    </div>
    <div class="crud">
        <a href="{% url 'updateblog' blog.id %}">
            <li>Düzəliş et</li>
        </a>
        <li class="delete-blog" data-id={{blog.id}}>Sil</li>
    </div>
    {% endif %}
    <div class="img">
        <img src="{{blog.image.url}}" alt="">
    </div>
    <div class="category">
        <div class="post-category">
            <p>{{blog.category}}</p>
        </div>

        <div class="stars"><i class="fa-regular fa-eye"></i> {% get_hit_count for blog %}</div>
    </div>
    <div class="title">
        <a href="{% url 'blogdetail' blog.slug %}">
            <h4>{{blog.title | truncatechars:40}}</h4>
        </a>
    </div>
    {% if blog.owner.id == user.profile.id %}
    <a href="{% url 'profile' user.profile.slug %}" class="profile">
        <div class="profile">
            <div class="profile-photo">
                {% if blog.owner.profile_image %}
                <img src="{{blog.owner.profile_image.url}}" alt="">

                {% endif %}
            </div>
            <div class="name-date">
                <p class="name">{{blog.owner.name}}</p>
                <p class="date">{{blog.created}}</p>
            </div>
        </div>
    </a>
    {% else %}
    <a href="{% url 'Account' blog.owner.slug %}" class="profile">
        <div class="profile">
            <div class="profile-photo">
                {% if blog.owner.profile_image %}
                <img src="{{blog.owner.profile_image.url}}" alt="">

                {% endif %}
            </div>
            <div class="name-date">
                <p class="name">{{blog.owner.name}}</p>
                <p class="date">{{blog.created}}</p>
            </div>
        </div>
    </a>
    {% endif %}

</div>

templates/partials/__categorycard.html
<div class="category-card">
    <div class="img">
        <img src="{{category.image.url}}" alt="">
    </div>
    <a href="{% url 'recipe-category' category.slug %}">
        <div class="title">
            <p>{{category.title}}</p>
            <span>({{category.blog_set.all|length}} resept)</span>
        </div>
    </a>
</div>

templates/partials/__comment.html
{% load static %}

<div class="comment-body"> {% if comment.owner == request.user.profile %}
    <div class="dots">
        <i class="fa-solid fa-ellipsis-vertical"></i>
    </div>

    <div class="crud">
        <li class="delete-comment" data-id={{comment.id}}>Sil</li>
    </div>{% endif %}
    <div class="img">
        {% if comment.owner.id == user.profile.id %}
        <a href="{% url 'profile' user.profile.slug %}"> <img src="{{comment.owner.profile_image.url}}">
    </div></a>
    {% else %}
    <a href="{% url 'Account' comment.owner.slug %}"> <img src="{{comment.owner.profile_image.url}}">
</div></a>
{% endif %}
<div class="comment-content">
    {% if comment.owner.id == user.profile.id %}
    <a href="{% url 'profile' user.profile.slug %}">
        <div class="comment-owner">
            <h3>{{comment.owner.name}}</h3>
            <small>@{{comment.owner.username}}</small>
        </div>
    </a>
    {% else %}
    <a href="{% url 'Account' comment.owner.slug %}">
        <div class="comment-owner">
            <h3>{{comment.owner.name}}</h3>
            <small>@{{comment.owner.username}}</small>
        </div>
    </a>
    {% endif %}
    <p class="time-created">{{comment.created}}</p>
    <p class="comment-text">{{comment.body|linebreaksbr}}</p>
</div>
</div>

templates/partials/__create_blog.html
{% load static %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <img id="preview" alt="Blog Image" src="{% static 'image/default.jpg' %}" />
  {{form.media}}
  {{form.as_p}}

  <div class="submit"> <input type="submit" value="Paylaş" /></div>
</form>

templates/partials/__modal.html
<div class="modal modal-delete-recipe">
    <form class="modal-content modal-recipe" method="POST">
        {% csrf_token %}
        <div class="close"><i class="fa-solid fa-xmark"></i></div>
        <lord-icon src="https://cdn.lordicon.com/wdqztrtx.json" trigger="hover" colors="primary:#ffba08"
            style="width:50px;height:50px">
        </lord-icon>
        <h1>Silmək İstədiyinizə Əminsiniz?</h1>
        <button type="submit">Sil</button>
    </form>
</div>

templates/partials/__paginations.html
<div class="pagination">

  {% if blog.has_previous %}
  <a href="?page={{ blog.previous_page_number }}{% if search_query %}&search_query={{ search_query }}{% endif %}"
    data-page="{{ blog.previous_page_number}}"><i class="fa-solid fa-angles-left"></i></a>
  {% endif %}
  {% for page in custom_range %}

  {% if page == blog.number %}
  <a href="?page={{ page }}{% if search_query %}&search_query={{ search_query }}{% endif %}" class="active page-link"
    data-page="{{page}}">{{page}}</a>
  {% else %}
  <a href="?page={{ page }}{% if search_query %}&search_query={{ search_query }}{% endif %}" class="page-link"
    data-page="{{page}}">{{page}}</a>
  {% endif %}

  {% endfor %}
  {% if blog.has_next %}
  <a href="?page={{ blog.next_page_number }}{% if search_query %}&search_query={{ search_query }}{% endif %}"
    data-page="{{ blog.next_page_number}}"><i class="fa-solid fa-angles-right"></i></a>
  {% endif %}

</div>

templates/partials/__recipecard.html
<div class="post-card">

    {% if blog.owner.id == user.profile.id %}
    <div class="dots">
        <i class="fa-solid fa-ellipsis-vertical"></i>
    </div>
    <div class="crud">
        <a href="{% url 'update' blog.id %}">
            <li>Düzəliş et</li>
        </a>
        <li class="delete-recipe" data-id={{blog.id}}>Sil</li>
    </div>
    {% else %}
    {% endif %}

    <div class="img">

        {% if blog.youtube_link %}
        <div class="play"><i class="fa-solid fa-play"></i></div>
        {% endif %}


        <img src="{{blog.image.url}}" alt="">
        <div class="heart">

            {% comment %} <i class="fa-regular fa-bookmark"></i> {% endcomment %}
            {% comment %} <i class="fa-solid fa-bookmark"></i> {% endcomment %}

        </div>
    </div>
    <div class="category">
        <a href="{% url 'recipe-category' blog.category.slug %}">
            <div class="post-category">
                <p>{{blog.category.title}}</p>
            </div>
        </a>
        <div class="time-cook"><i class="fa-regular fa-clock"></i> {{blog.cook_time}} {{blog.time}}</div>
        {% if blog.isActive %}
        {% else %}
        <div class="time-cook pending"> Gözləmədədir</div>
        {% endif %}
        <div class="stars"><i class="fa-solid fa-thumbs-up"></i>{{blog.vote_set.all | length }}</div>
        <div class="comment"><i class="fa-solid fa-comment"></i>{{blog.review_set.all | length}}</div>
    </div>
    <div class="title"><a href="{% url 'blogdetails' blog.slug %}">
            <h4>{{blog.title | truncatechars:50}}</h4>
        </a>
    </div>


    <a href="{% if blog.owner.id == user.profile.id %} {% url 'profile' user.profile.slug %} {% else %} {% url 'Account' blog.owner.slug %} {% endif %}"
        class="profile">
        <div class="profile">
            <div class="profile-photo">
                {% if blog.owner.profile_image %}
                <img src="{{blog.owner.profile_image.url}}" alt="">
                {% endif %}
            </div>
            <div class="name-date">
                <p class="name">{{blog.owner.name}}</p>
                <p class="date">{{blog.created}}</p>
            </div>
        </div>
    </a>


</div>