blog/urls.py
from django.urls import path
from . import views


urlpatterns=[
   path('blogs/', views.blog, name="blogs"),
   path('create-blog/',views.createBlog, name="createblog"),
   path('blog-details/<slug:slug>', views.details, name="blogdetail"),
   path('update-blog/<str:pk>/', views.updateBlog, name="updateblog"),
   path('delete-blog/<str:pk>/', views.deleteBlog, name="deleteBlog"),
]

setting/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve 

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('recipes.urls')),
    path('', include('blog.urls')),
    path('',include('main.urls')),
    path('notification/',include('notification.urls')),

    #Reset Password

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="confirm_password.html"), name="password_reset_complete")

]

handler404 = 'main.views.error_404_view'
handler500 = 'main.views.error_500'

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]


admin.site.site_header = "yemake.com"
admin.site.site_title = "YeMake"

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('signout/', views.signout, name="signout"),  
    path('profiles/',views.users, name="contact"), 
    path('edit-account/', views.editAccount, name='edit-account'),path('user/<slug:slug>/',views.userAccount, name="Account"),  
    path('account/<slug:slug>/',views.myprofile, name="profile"),     
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify



# Create your models here.


class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE, null=True )
    username=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=200, null=True, blank=True)
    email=models.EmailField(max_length=200,null=True,blank=True, unique=True)
    short_info=models.CharField(max_length=200, null=True, blank=True)
    profile_image=models.ImageField(upload_to='Users', null=True, blank=True,default='Users/user-default.jpg')
    cover_image=models.ImageField(upload_to='Users', blank=True, null=True, default='Users/cover.webp')
    slug=models.SlugField( verbose_name="Slug", null=True, unique=True)

    def __str__(self) -> str:
        return str(self.slug)

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.user.username)
        return super().save(*args, **kwargs)



 

users/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User

        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            "first_name": "Ad Soyad",
            'username': 'İstifadəçi Adı'
        }

    def __init__(self, *args, **kwargs):
      super(CustomUserCreationForm, self).__init__(*args, **kwargs)
      for name, field in self.fields.items():
         field.widget.attrs.update({'class': 'input-signup'})
      self.fields['first_name'].widget.attrs['placeholder'] = 'Ad Soyad'
      self.fields['email'].widget.attrs['placeholder'] = 'Email'
      self.fields['username'].widget.attrs['placeholder'] = 'İstifadəçi Adı'
      self.fields['password1'].widget.attrs['placeholder'] = 'Şifrə'
      self.fields['password2'].widget.attrs['placeholder'] = 'Təkrar Şifrə'

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email artıq mövcuddur")
        return email
    

class ProfileForm(ModelForm):
    class Meta:
        model=Profile
        email=forms.CharField(error_messages={'unique': u'My custom message'}) 
        fields=["name","cover_image","profile_image","username","short_info"]
        labels = {
            "cover_image": "Örtük Şəkli",
            'profile_image': 'Profil Şəkli',
            "name":"Ad Soyad",
            "username":"İstifadəçi Adı",
            "short_info":"Qısa Məlumat",
        }
       
            
            
       
            

users/views.py
from dataclasses import field
from email import message
from django.shortcuts import render, redirect
from .models import Profile
from recipes.models import Blog
from blog.models import Blog as Blg
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, ProfileForm
from django.db.models import Count
# Create your views here.



@login_required(login_url='signin')
def myprofile(request, slug):
    profile=request.user.profile
    page='profile'
    recipes=Blog.objects.filter(owner__username=profile.username).order_by("-created")
    blogs=Blg.objects.filter(owner__username=profile.username).order_by("-created")
    book=profile.recipebook_set.all() 
    review=profile.review_set.count()
    
    context={
        "profile":profile,
        "recipes":recipes,
        "blogs":blogs,
        "page":page,
        "book":book,
        "review":review,
   
    }
    return render(request, 'users/user_profile.html',context)


def signin(request):
    page='signin'
    if request.user.is_authenticated:
        return redirect('profile')


    if request.method=='POST':
        username=request.POST['username'].lower()
        password=request.POST['password']

        try:
            user=User.objects.get(username=username)
            messages.success(request="Uğurla Giriş Etdiniz")
        except:
            pass
        
        user=authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET["next"] if "next" in request.GET else "index")
        else:
            messages.error(request, "İstifadəçi adı və ya şifrə yanlışdır.")


    return render(request, 'users/signin.html')




def signout(request):
  
    logout(request)
    return redirect('index')


def signup(request):
    page='signup'
    form=CustomUserCreationForm()
    if request.method=='POST':
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.lower()
            user.save()
            login(request, user)
            return redirect("edit-account")

    context={
        "page":page,
        "form":form
    }
    return render(request, 'users/signin.html', context)

def userAccount(request, slug):
    page='Account'
    profile=Profile.objects.get(slug=slug)
    user_recipes=Blog.objects.filter(owner__slug=profile.slug).order_by("-created")
    user_blogs=Blg.objects.filter(owner__username=profile.username).order_by("-created")
    user_book=profile.recipebook_set.all() 
    user_review=profile.review_set.count()
    context={
        "profil":profile,
        "page": page,
        "user_recipes":user_recipes,
        "user_blogs":user_blogs,
        "user_book":user_book,
        "user_review":user_review
    }
    return render(request, "users/user_profile.html", context )
    

def users(request):
    profiles=Profile.objects.all()
    context={
        "profiles":profiles
    }
    return render(request, "contact.html",context)

@login_required(login_url='signin')
def editAccount(request):
    profile=request.user.profile
    form=ProfileForm(instance=profile)
    if request.method=="POST":
        form=ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(f'/account/{profile.slug}')

    context={
        "form":form
    }
   
    return render(request, "users/profile_form.html",context)

templates/users/profile_form.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href='{% static '/css/profile-form.css' %}?{% now "U" %}'>
<link rel="stylesheet" href='{% static '/css/output.css' %}?{% now "U" %}'>

{% endblock css %}


{% block title %}
<title>Tənzimləmələr</title>

{% endblock title %}

{% block content %}
<h3 class="title">Profilini Tənzimlə</h3>
<div class="profile-form">
  <div class="form">

    <form action="{% url 'edit-account' %}" method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      <div class="profile-relative-div">
        <div class="cvr-img">
          <img src="" alt="cover-photo" id="cvr-img">
          <label for="id_cover_image"><i class="fa-regular fa-pen-to-square"></i></label>
          <div class="hide">{{form.cover_image}}</div>
        </div>
        <div class="prf-img">
          <img src="" alt="profile-photo" id="prf-img">
          <label for="id_profile_image">Profil Şəklini Dəyiş</label>
          <div class="hide">{{form.profile_image}}</div>
        </div>
      </div>


      <div class="field">
        <label for="id_name">{{form.name.label}}</label>
        {{form.name}}
        <label for="id_username">{{form.username.label}}</label>
        {{form.username}}
        <label for="id_short_info">{{form.short_info.label}}</label>
        {{form.short_info}}
      </div>

      {% for error in field.errors %}
      <p class="error">{{error}}</p>
      {% endfor %}

      <div class="flex justify-center">
        <button type="submit"
          class="text-white  focus:outline-none  font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Təsdiqlə</button>
      </div>
    </form>
  </div>

</div>

{% endblock content %}

{% block js %}

<script src='{% static '/js/profile_form.js' %}?{% now "U" %}'></script>

{% endblock js %}

templates/users/signin.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

<link rel="stylesheet" href='{% static '/css/login.css' %}?{% now "U" %}'>

{% endblock css %}

{% block title %}<title>Giriş Et</title>{% endblock  %}
{% block content %}

<!----- QEYDIYYATDAN KEÇ SƏHİFƏSİ ----->

{% if page == 'signup' %}
<div class="container">
  <div class="formBx">
    <form method='POST' action="{% url 'signup' %}">
      {% csrf_token %}
      <h2>Qeydiyyatdan Keç</h2>
      {% for field in form %}
      <label for="formInput#text">{{field.label}}</label>
      <div class="{% if field.errors %}error-div{% else %}input-div{% endif %}">
        {{field}}
      </div>
      {% comment %} {% if field.help_text %}
      <small>{{field.help_text}}</small><br>
      {% endif %} {% endcomment %}


      {% for error in field.errors %}
      <p class="error">{{error}}</p>
      {% endfor %}
      {% endfor %}
      <br>
      <input type="submit" value="Qeydiyyat" />
      <p class="signup">
        Hesabın var mı? <a href="{% url 'signin' %}">Giriş Et</a>
      </p>
    </form>
  </div>
  <div class="imgBx">
    <img src="{% static 'image/signup.jpeg' %}" alt="" />
  </div>
</div>

{% else %}

<!-- GİRİŞ ET SƏHİFƏSİ -->

<section>
  <div class="container">
    <div class="imgBx">
      <img src="{% static 'image/login.jpeg' %}" alt="" />
    </div>
    <div class="formBx">
      <form action="" method="POST">
        {% csrf_token %}
        <h2>Giriş Et</h2>
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        <input type="text" placeholder="İstifadəçi Adı" name="username" />
        <input type="password" placeholder="Şifrə" name="password" />
        <div class="card-footer">
          <input type="submit" value="Giriş Et" />
          <a href="{% url 'reset_password' %}">Şifrəni Unutdun?</a>
        </div>
        <p class="signup">
          Hesabın yoxdur? <a href="{% url 'signup' %}">Qeydiyyatdan Keç</a>
        </p>
      </form>
    </div>

  </div>
</section>
{% endif %}

{% endblock content %}

templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href='{% static '/css/index.css' %}?{% now "U" %}'>
<link rel="stylesheet" href='{% static '/css/user-profile.css' %}?{% now "U" %}'>


{% endblock css %}

{% block title %}<title>Profil</title>{% endblock title %}

{% block content %}
<div class="modal mdl">
  <div class="modal-image">
    <img src="" alt="" id="modal-view">
    <div class="close"><i class="fa-solid fa-xmark"></i></div>
  </div>
</div>

{% if page == "profile" %}

<div class="background">
  <div class="bg-img"><img src="{{profile.cover_image.url}}" alt=""></div>
</div>
<div class="all-datas">
  <div class="profile-image">

    <div class="prf-image"><img src="{{profile.profile_image.url}}" alt=""></div>
  </div>
  <div class="profile-name">
    <h1>{{profile.name}}</h1>
    <small>@{{profile.username}}</small>
    <div class="user-count box">
      <a href="#recipes">
        <div class="count-box">
          <h3>{{recipes | length}}</h3>
          <p>resept</p>
        </div>
      </a>
      <a href="#blogs">
        <div class="count-box">
          <h3>{{blogs | length}}</h3>
          <p>blog</p>
        </div>
      </a>
      <div class="count-box">
        <h3>{{review}}</h3>
        <p>şərh</p>
      </div>
    </div>
    <div class="line"></div>
    <p>{{profile.short_info}}</p>
    {% if user.is_superuser %}
    <a href="{% url 'newsletter' %}" class="btn-news" type="button">
      NewsLetter
    </a>
    {% endif %}
  </div>
  <div class="bottom-profile padding-x">
    <div class="recipes underline-div" id="recipes">
      <p class="head-post">Reseptlərim ({{recipes | length}})</p> <a href="{% url 'blogcreate' %}" class="btn"><i
          class="fa-solid fa-plus"></i> Resept Əlavə Et</a>
    </div>
    <div class="cards">
      {% if recipes %}

      {% for blog in recipes %}
      <div class="card">
        {% include "partials/__recipecard.html" %}
      </div>
      {% endfor %}
      {% else %}
      <h2>Ups... Resept paylaşmamısan?😒</h2>
      {% endif %}


    </div>
    <div class="blogs underline-div" id="blogs">
      <p class="head-post">Bloglarım ({{blogs | length}})</p><a href="{% url 'createblog' %}" class="btn"><i
          class="fa-solid fa-plus"></i> Blog Əlavə Et</a>
    </div>
    <div class="cards">
      {% if blogs %}
      {% for blog in blogs %}
      <div class="card">
        {% include "partials/__blogcard.html" %}
      </div>
      {% endfor %}
      {% else %}
      <h2>Ups... Blog paylaşmırsan?😯</h2>
      {% endif %}
    </div>
    <div class="wishlist underline-div">
      <p class="head-post">Resept Kitabım ({{book | length}}) </p>

    </div>
    <div class="cards">
      {% if book %}
      {% for blog in book %}
      <div class="card">
        {% include "partials/__recipecard.html" with blog=blog.recipe %}</div>
      {% endfor %}
    </div>
    {% else %}

    <h2>Ups... Resept dəftərin boşdur?🤨</h2>
    {% endif %}
  </div>
</div>
</div>



{% else %}

<div class="background">
  <div class="bg-img"><img src="{{profil.cover_image.url}}" alt=""></div>
</div>
<div class="all-datas">
  <div class="profile-image">

    <div class="prf-image"><img src="{{profil.profile_image.url}}" alt=""></div>
  </div>
  <div class="profile-name">
    <h1>{{profil.name}}</h1>
    <small>@{{profil.username}}</small>
    <div class="user-count box">
      <a href="#recipes">
        <div class="count-box">
          <h3>{{user_recipes | length}}</h3>
          <p>resept</p>
        </div>
      </a>
      <a href="#blogs">
        <div class="count-box">
          <h3>{{user_blogs | length}}</h3>
          <p>blog</p>
        </div>
      </a>
      <div class="count-box">
        <h3>{{user_review}}</h3>
        <p>şərh</p>
      </div>
    </div>
    <div class="line"></div>
    {% if profil.short_info %}
    <p>{{profil.short_info}}</p>
    {% endif %}

  </div>
  <div class="bottom-profile padding-x">
    <div class="recipes underline-div" id="recipes">
      <p class="head-post">Reseptlər ({{user_recipes | length}})</p>
    </div>
    <div class="cards">
      {% if user_recipes %}

      {% for blog in user_recipes %}
      {% if blog.isActive %}
      <div class="card">
        {% include "partials/__recipecard.html" %}
      </div>
      {% endif %}
      {% endfor %}
      {% else %}
      <h2>Ups... Resept paylaşmayıb?😒</h2>
      {% endif %}


    </div>
    <div class="blogs underline-div" id="blogs">
      <p class="head-post">Bloglar ({{user_blogs | length}})</p>
    </div>
    <div class="cards">
      {% if user_blogs %}
      {% for blog in user_blogs %}
       {% if blog.isActive %}
      <div class="card">
        {% include "partials/__blogcard.html" %}
      </div>{% endif %}
      {% endfor %}
      
      {% else %}
      <h2>Ups... Blog paylaşmayıb?😯</h2>
      {% endif %}
    </div>
    <div class="wishlist underline-div">
      <p class="head-post">Resept Kitabı ({{user_book | length}}) </p>

    </div>
    <div class="cards">
      {% if user_book %}
      {% for blog in user_book %}
      <div class="card">
        {% include "partials/__recipecard.html" with blog=blog.recipe %}</div>
      {% endfor %}
    </div>
    {% else %}

    <h2>Ups... Resept dəftəri boşdur?🤨</h2>
    {% endif %}
  </div>
</div>
</div>


{% endif %}

{% endblock content %}